#!/bin/bash

METAR_DATA=$(curl -s "https://aviationweather.gov/api/data/metar?ids=KMCI&format=json&taf=false&hours=12&bbox=40%2C-90%2C45%2C-85")
RECEIPT_TIMES=$(echo "$METAR_DATA" | jq -r '.[] | .receiptTime')
echo "$RECEIPT_TIMES" | head -n 6
