#!/home/gitpod/.pyenv/shims/python

import json

with open('/workspace/json-practice/data/schacon.repos.json', 'r') as file:
    data = json.load(file)

with open('chacon.csv', 'a') as csvfile:
    for entry in data[:5]:
        name = entry['name']
        html_url = entry['html_url']
        updated_at = entry['updated_at']
        visibility = entry['visibility']
        
        csvfile.write(f"{name},{html_url},{updated_at},{visibility}\n")
